#! /usr/bin/bash
export LC_COLLATE=C
shopt -s extglob

clear
echo -en "${GREEN}========================================================================================= ${NC}\n "
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color 

fileo=$1

columns=($(awk -F: '{print $1}' "$fileo-meta"))
type=($(awk -F: '{print $2}' "$fileo-meta"))
fk=($(awk -F: '{print $1}' "$fileo"))
array_length=${#columns[@]}
insert_data() {
my_string=""
countItem=0

                 echo -en "${BLUE} you can enter  Ctrl + C to exit from any operation ${NC}\n"
for (( index=0; index<$array_length; index++ ))
 do
((countItem))
                # echo -en "${BLUE}enter the number of column :  you can enter  Ctrl + C to exit from any operation ${NC}\n"
    echo "Index $index: ${columns[index]}"
   read -p " enter the ${columns[index]} : the data type is ${type[index]} " value


############### prevent user enter  value conatain :
if [[ $value == *":"* ]]; then

       echo -en " ${RED}Error: Input contains the ':' character, which is not allowed. ${NC} "
        ((index--))
        continue
fi

##############################################3
###################### check  empty value
value_trimmedins="$(echo -e "${value}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

if [ -z "$value_trimmedins" ]; then

    echo -en " ${RED}Empty value or contains only spaces not available please enter real data. ${NC} "
    ((index--))
     continue
fi
 


############## check FK
if [[ $index -eq 0 ]]; then
       
 
flagz=1
	for valo in "${fk[@]}"; do
			if [[ "$valo" == "$value_trimmedins" ]]; then
			echo -en " ${RED}value  '$value' already exists. Enter a different unique value. this primary key column ${NC} "
			((index--))
			flagz=0   
			 break
			 fi
	done



	if [[ $flagz -eq 0 ]]; then

	    continue

	fi

fi
############### check valid number
if [[  ${type[index]} = "integer" ]]; then
        if [[ ! $value =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
	    #echo "please enter valid number"
            echo -en " ${RED}please enter valid number ${NC} "
	      ((index--))
		continue
	fi
 
fi 


  
  my_string+="$value:"
  trimmed_text=$(echo -e "${my_string}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
 
text_length=${#trimmed_text}
final_text="${trimmed_text:0:$((text_length-1))}"

done
   

    # Append the new record to the data file
   # echo "$id,$name,$email" >> "$data_file"
##########################3



    echo "$final_text" >> $fileo
    
    echo  -en "${GREEN} Data inserted successfully! >> $final_text ${NC}"

 

########################
    
}
#insert_data

while :
do
    echo "Database insert  Operations: chose "
    echo "1. to Insert Data"
    echo "2. to  Exit"
    

    read -p "Enter your choice: " choice

    case $choice in
        1) insert_data
               break
                ;;
        2) echo "Exiting... to prevois menue"; break;;
        
        *) echo "Invalid choice"
                   continue
                ;;
    esac
done
